CREATE TABLE MYBATISBOARD(
NO NUMBER, 
TITLE VARCHAR2(100) NOT NULL, 
CONTENT VARCHAR2(500) NULL, 
WRITER VARCHAR2(50) NOT NULL, 
REG_DATE DATE DEFAULT SYSDATE 
); 

ALTER TABLE MYBATISBOARD ADD CONSTRAINT MYBATISBOARD_PK PRIMARY KEY(NO);

CREATE SEQUENCE MYBATISBOARD_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE TABLE member(
NO NUMBER,
ID VARCHAR2(50) NOT NULL,
PW VARCHAR2(50) NOT NULL, 
NAME VARCHAR2(100) NOT NULL,
COIN NUMBER(10) DEFAULT 0,
REG_DATE DATE DEFAULT SYSDATE,
UPD_DATE DATE DEFAULT SYSDATE, 
ENABLED CHAR(1) DEFAULT '1'
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(NO);

CREATE TABLE MEMBER_AUTH( 
NO NUMBER NOT NULL, 
AUTH VARCHAR2(50) NOT NULL
);

CREATE TABLE MEMBER_EMAIL(
NO NUMBER NOT NULL,
EMAIL VARCHAR2(50) NOT NULL
);

ALTER TABLE MEMBER_EMAIL ADD CONSTRAINT MEMBER_EMAIL_NO_FK 
FOREIGN KEY(NO) REFERENCES MEMBER(NO) ON DELETE CASCADE;

INSERT INTO MEMBER(NO,ID,PW,NAME)
VALUES(MEMBER_SEQ.NEXTVAL,'AAA','123456','KDJ');

delete from member;

create sequence MEMBER_SEQ
start with 1
increment by 1;

drop sequence member_seq;
INSERT INTO MEMBER_AUTH(NO,AUTH)VALUES(6,'MEMBER');
SELECT * FROM MEMBER_EMAIL;



select MEMBER_SEQ.NEXTVAL FROM DUAL;

select * from MEMBER;
-- 회원가입
INSERT INTO MEMBER_AUTH (NO, AUTH) VALUES(1, 'ADMIN');
commit;

SELECT MEMBER_SEQ.NEXTVAL FROM DUAL;
--회원, 권한 조인
SELECT M.NO, M.ID, PW, NAME, REG_DATE, UPD_DATE,AUTH,EMAIL 
FROM MEMBER M
LEFT OUTER JOIN MEMBER_AUTH A ON M.NO = A.NO
LEFT OUTER JOIN MEMBER_EMAIL E ON M.NO = E.NO
WHERE M.NO = 1;
--회원 정보 요청
SELECT NO, ID, PW, NAME, REG_DATE FROM MEMBER ORDER BY REG_DATE DESC;
--회원 수정
UPDATE MEMBER
SET NAME = 'SSSS' WHERE NO = 1;
--회원 삭제
DELETE FROM MEMBER WHERE NO = 1;
--권한 삭제
DELETE FROM MEMBER_AUTH WHERE NO = 1;

select * from board;

ROLLBACK;

--AOP Table
CREATE TABLE AOPBOARD(
NO NUMBER,
TITLE VARCHAR2(100) NOT NULL,
CONTENT VARCHAR2(1000) NULL,
WRITER VARCHAR2(50) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE,
PRIMARY KEY (NO)
);
CREATE SEQUENCE AOPBOARD_SEQ
START WITH 1
INCREMENT BY 1;

desc aopboard;
select * from aopboard;